#!/usr/bin/env python3
"""Copy the shared page chrome (partials/*.html) into every site page.

Each page carries three marker pairs:

    <!-- site:assets --> ... <!-- /site:assets -->   (in <head>)
    <!-- site:header --> ... <!-- /site:header -->   (start of <body>)
    <!-- site:footer --> ... <!-- /site:footer -->   (end of <body>)

The text between a pair is replaced by the matching partial, with {{root}} set to the page's
relative path to the site root and {{v}} set to partials/ASSET_VERSION. The link whose
data-nav equals the page's <body data-nav="..."> gets aria-current="page". A page served at
any depth (404.html) sets <body data-root="/"> to get absolute links instead.

    python3 scripts/sync_layout.py          # rewrite pages in place
    python3 scripts/sync_layout.py --check  # exit 1 if any page is out of date

The Portugal product page is generated by databoutique-pilot (scripts/portugal/site_page.py),
which applies the same partials with the same rules.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARTS = ("assets", "header", "footer")
SKIP_DIRS = ("preview", "delta-force", "api", "downloads", "samples", "partials", "scripts", "node_modules")
_NAV = re.compile(r'<body[^>]*\sdata-nav="([a-z-]+)"')


def pages(root: Path = ROOT):
    for p in sorted(root.rglob("*.html")):
        rel = p.relative_to(root)
        if rel.parts[0] in SKIP_DIRS:
            continue
        yield p


def load_partials(root: Path = ROOT):
    version = (root / "partials" / "ASSET_VERSION").read_text(encoding="utf-8").strip()
    return version, {name: (root / "partials" / f"{name}.html").read_text(encoding="utf-8").strip() for name in PARTS}


def render(partial: str, rel_root: str, version: str, nav: str) -> str:
    out = partial.replace("{{root}}", rel_root).replace("{{v}}", version)
    if nav:
        out = out.replace(f'data-nav="{nav}"', f'data-nav="{nav}" aria-current="page"')
    return out


_ROOT_OVERRIDE = re.compile(r'<body[^>]*\sdata-root="([^"]+)"')


def apply(text: str, depth: int, version: str, partials) -> str:
    # 404.html is served at any depth, so it asks for absolute links with <body data-root="/">.
    o = _ROOT_OVERRIDE.search(text)
    rel_root = o.group(1) if o else "../" * depth
    m = _NAV.search(text)
    nav = m.group(1) if m else ""
    for name in PARTS:
        start, end = f"<!-- site:{name} -->", f"<!-- /site:{name} -->"
        if start not in text or end not in text:
            raise ValueError(f"missing {start} ... {end}")
        body = render(partials[name], rel_root, version, nav)
        text = re.sub(re.escape(start) + r".*?" + re.escape(end),
                      lambda _: f"{start}\n  {body}\n  {end}", text, count=1, flags=re.S)
    return text


def main(argv=None) -> int:
    check = "--check" in (argv if argv is not None else sys.argv[1:])
    version, partials = load_partials()
    stale = []
    for page in pages():
        depth = len(page.relative_to(ROOT).parts) - 1
        old = page.read_text(encoding="utf-8")
        try:
            new = apply(old, depth, version, partials)
        except ValueError as exc:
            print(f"{page.relative_to(ROOT)}: {exc}")
            return 1
        if new != old:
            stale.append(page.relative_to(ROOT))
            if not check:
                page.write_text(new, encoding="utf-8")
    if check and stale:
        for p in stale:
            print(f"out of date: {p}")
        return 1
    print(f"{'checked' if check else 'synced'} {len(list(pages()))} pages, asset version {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
